blank_issues_enabled: true
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/gundambox/MyAuthService/blob/main/CONTRIBUTING.md
    about: Please read the contributing guidelines before creating an issue
